name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: REST API call
        id: rs get transformation
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.rudderstack.com/transformations/2M5a8oQAtGAsLopL6UxQ3rjKdTo/versions'
          method: 'GET'
          username: 'pierre-yves@fatmap.com'
          password: '2NSsUj2JqOpiZSsAW5FF5UHYtf5'
          customHeaders: '{"Content-Type": "application/json"}'
      - name: show api response
        run: echo ${{ steps.myRequest.outputs.response }}
      #  run: curl -X GET -H "Authorization: Basic cGllcnJlLXl2ZXNAZmF0bWFwLmNvbToyTlNzVWoySnFPcGlaU3NBVzVGRjVVSFl0ZjU=" \ 'https://api.rudderstack.com/transformations/2M5a8oQAtGAsLopL6UxQ3rjKdTo/versions'
      #- run: curl --location 'api.rudderstack.com/transformations/2M5a8oQAtGAsLopL6UxQ3rjKdTo' --header 'Authorization: Basic cGllcnJlLXl2ZXNAZmF0bWFwLmNvbToyTlNzVWoySnFPcGlaU3NBVzVGRjVVSFl0ZjU='
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."